### ISSUE TITLE
Cannot be scaned in  bitwig5.0.4 on  Ubuntu2204.

### ISSUE THREAD

**Issue by Huayuluoshi** [liuanlin-mx/MXComp#1]
Like  title  says.
ThinkPad-T440
What  else do  you  want  me  post?Let me konw.Thank  you  for  your  help !

**Comment by liuanlin-mx** [comment]
try 
sudo apt install libfftw3-dev
Rescan plug-in

**Comment by Huayuluoshi** [comment]
> try sudo apt install libfftw3-dev Rescan plug-in

I am so sorry to workaround...
![图片](https://github.com/liuanlin-mx/MXComp/assets/117527694/6b679280-7081-41b3-a9e9-c9946b2ac33c)

![图片](https://github.com/liuanlin-mx/MXComp/assets/117527694/c559cd67-14de-434e-a560-97f4bee0147d)

**Comment by liuanlin-mx** [comment]
Sorry,   
It should be this
sudo apt install libglfw3

**Comment by Huayuluoshi** [comment]
> Sorry, It should be this sudo apt install libglfw3

Thank you.The plugin worked  correctly.But I suggest you  write  them in  readme file,because others can solve  the  same  problem ,thanky you  again !
